In [1]:
import pandas as pd

In [3]:
result = pd.read_csv('results.csv')

,titles,companies,links,date_listed
0,Software Engineer\nnew,A2000 Solutions Pte Ltd,www.Indeed.co.uk//rc/clk?jk=7d3a477772f62a2e&f...,Just posted
1,Software Engineer/ Programmer - Training Provi...,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
2,Business Development Manager (IT/ Software)\nnew,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
3,Maintenance Engineer (SCADA & Substation Autom...,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
4,Automation Engineer\nnew,ATS Automation Tooling Systems Inc.,www.Indeed.co.uk//rc/clk?jk=90469b0a39801802&f...,Just posted

In [4]:
result

,titles,companies,links,date_listed
0,Software Engineer\nnew,A2000 Solutions Pte Ltd,www.Indeed.co.uk//rc/clk?jk=7d3a477772f62a2e&f...,Just posted
1,Software Engineer/ Programmer - Training Provi...,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
2,Business Development Manager (IT/ Software)\nnew,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
3,Maintenance Engineer (SCADA & Substation Autom...,Anradus Pte Ltd,www.Indeed.co.uk//company/Anradus-Pte-Ltd/jobs...,Just posted
4,Automation Engineer\nnew,ATS Automation Tooling Systems Inc.,www.Indeed.co.uk//rc/clk?jk=90469b0a39801802&f...,Just posted
...,...,...,...,...
1120,.NET Core Senior Full-stack Developer (Permanent),Page Personnel,www.Indeed.co.uk//pagead/clk?mo=r&ad=-6NYlbfkN...,30+ days ago
1121,Android Developer - Global eCommerce Brand,Page Personnel,www.Indeed.co.uk//pagead/clk?mo=r&ad=-6NYlbfkN...,30+ days ago
1122,C#.NET Software Developer - Technology Brand,Page Personnel,www.Indeed.co.uk//pagead/clk?mo=r&ad=-6NYlbfkN...,30+ days ago
1123,Full Stack Developer,Respiree Pte Ltd,www.Indeed.co.uk//pagead/clk?mo=r&ad=-6NYlbfkN...,30+ days ago
1124,Computer Vision & ML Developer,XRVision,www.Indeed.co.uk//pagead/clk?mo=r&ad=-6NYlbfkN...,30+ days ago